// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type Order struct {
	ID        int32            `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type OrderProduct struct {
	OrderID   int32 `json:"order_id"`
	ProductID int32 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
}

type Product struct {
	ID             int32          `json:"id"`
	Name           string         `json:"name"`
	Description    pgtype.Text    `json:"description"`
	Price          pgtype.Numeric `json:"price"`
	InventoryCount int32          `json:"inventory_count"`
}

type Token struct {
	Hash      []byte             `json:"hash"`
	AdminID   int32              `json:"admin_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}
