// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type Product struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Price       pgtype.Numeric `json:"price"`
}

type Token struct {
	Hash    []byte             `json:"hash"`
	AdminID int32              `json:"admin_id"`
	Expiry  pgtype.Timestamptz `json:"expiry"`
}
