// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID          int32
	Name        pgtype.Text
	Description pgtype.Text
	Price       pgtype.Numeric
}
